import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const popins = Poppins({
	weight: ['400', '600', '700'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Goodlyfe Gym',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={popins.className}>{children}</body>
		</html>
	)
}
